image: node:alpine


stages:
  - build



cache:
  paths:
    - node_modules/  # Cache node_modules directory to speed up builds

build:
  stage: build
  script:
    - npm install  # Install project dependencies
    - npx tsc
    - npx expo export  # Export the Expo project
    - npm run expoConfig  # Generate expoConfig.json
    - npm run store-publish

  only:
    - main

